---

- name: Install default Apache Web Server
  hosts: ungrouped
  become: yes

  tasks:

  - name: Stoped Apache and Enable on every boot
    service:
      name: apache2
      state: stopped
      enabled: no

  - name: Remove Apache Web Server
    apt:
      name: apache2
      state: absent


