---

- name: Install default Apache Web Server
  hosts: 178.250.187.15
  become: yes

  tasks:

  - name: Install Apache Web Server
    apt:
      name: apache2
      state: latest

  - name: Start Apache and Enable on every boot
    service:
      name: apache2
      state: started
      enabled: yes
