---

- name: Install Apache and Upload my Web Page
  hosts: ungrouped
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html/index.html

  tasks:

  - name: Check and Print Linux Version
    debug:
      var: ansible_os_family

  - name: Install Apache Web Server for Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: Install Apache Web Server for RedHat
    yam:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Copy MyHomePage to Servers
    copy:
      src: "{{ source_file }}"
      dest: "{{ destin_file }}"
      mode: '0555'
    notify: Restart Apache

  - name: Start Apache and Enable on the every boot
    service:
      name: apache2
      state: started
      enabled: yes

  handlers:
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
