---

- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  tasks:

  - name: Loop Until example.
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final Output.
    debug:
      var: output.stdout


